### ISSUE TITLE
Consider using EnvVarRequirement to set BLASTDB path

### ISSUE THREAD

**Issue by christiam** [ncbi/cwl-demos#3]
Applies to https://github.com/ncbi/cwl-demos/tree/master/outlier-hit-detection-pipeline.

E.g.:
```
requirements:
- class: EnvVarRequirement
  envDef:
  - envName: BLASTDB
    envValue: $(inputs.blastdb_dir.path)
````
